fix: fix requset error & fix navigate push port bug
raxjs/universal-api pull request #163
Opened 2021-05-26 11:14 UTC by DOBEEE

2021-05-26 11:18 UTC, brightcd approved these changes

2021-05-26 12:08 UTC, ChrisCindy commented on src/packages/interactive/toast/CHANGELOG.md
> +* 修复web侧自执行逻辑在其它容器报错的问题
中英文空格问题注意下

2021-06-01 03:07 UTC, ChrisCindy requested changes

2021-06-01 03:07 UTC, ChrisCindy commented on src/packages/navigate/src/web/push.ts
> +  //   `${location.protocol}//${location.host}/${location.pathname.split('/').filter((i) => !!i).join('/')}${location.search ? location.search : '/'}#${url}` : url;
注释处理一下

2021-06-01 03:24 UTC, ChrisCindy approved these changes

2021-06-01 03:25 UTC, merged